ARG BASE_IMAGE="ghcr.io/gbraad-dotfiles/fedora"
ARG BASE_VERSION="41"

FROM ${BASE_IMAGE}:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/podman-machine-os"

USER root

RUN dnf install -y \
        podman skopeo buildah oras \
    && dnf clean all \
    && rm -rf /var/cache/yum


  
ENTRYPOINT ["/sbin/init"]
#CMD ["/sbin/init"]
